### ISSUE TITLE
`impt log stream` fails with HTTP/400 behind Proxy Server

### ISSUE THREAD

**Issue by deldrid1** [EatonGMBD/imp-central-impt#4]
This works fine when not behind a proxy server, but even with environment variables set (and commands like `impt build run` working fine), this command fails

```bash
$ impt log stream -d 30000c2a690e506b -z debug
Doing the request with options:
{
  "url": "https://api.electricimp.com/v5/devices/30000c2a690e506b",
  "method": "GET",
  "headers": {
    "Content-type": "application/vnd.api+json",
    "Authorization": "[hidden]"
  },
  "json": true,
  "qs": null,
  "body": null,
  "qsStringifyOptions": {
    "arrayFormat": "repeat"
  },
  "forever": true
}

Response code: 200
Response headers: {
  "date": "Wed, 29 Jan 2020 14:29:09 GMT",
  "content-type": "application/vnd.api+json",
  "transfer-encoding": "chunked",
  "connection": "close",
  "server": "nginx/1.10.3 (Ubuntu)",
  "content-language": "en",
  "x-node": "api02",
  "cache-control": "no-cache, no-store, must-revalidate",
  "pragma": "no-cache",
  "expires": "0",
  "accept": "application/vnd.api+json",
  "x-ratelimit-limit": "30",
  "x-ratelimit-reset": "1",
  "x-ratelimit-remaining": "29",
  "strict-transport-security": "max-age=1209600"
}
Response body: {
  "data": {
    "type": "device",
    "id": "30000c2a690e506b",
    "attributes": {
      "name": null,
      "agent_id": "RgxQQpulZlbd",
      "agent_url": "https://agent.electricimp.com/RgxQQpulZlbd",
      "device_online": true,
      "device_state_changed_at": "2020-01-28T02:34:36.332Z",
      "agent_running": true,
      "agent_state_changed_at": "2020-01-16T17:46:44.670Z",
      "last_enrolled_at": "2020-01-16T17:47:12.080Z",
      "imp_type": "imp003",
      "ip_address": "107.107.59.163",
      "tags": null,
      "mac_address": "0c:2a:69:0e:50:6b",
      "free_memory": 110412,
      "rssi": -60,
      "swversion": "882c579 - release-40.11 - Wed Oct  2 10:41:02 2019 - production",
      "plan_id": "12e9c4cbcb239574"
    },
    "relationships": {
      "owner": {
        "type": "account",
        "id": "bd81b713-4e56-cb4b-eea9-a0949cae9445"
      },
      "product": {
        "type": "product",
        "id": "466a0f31-54a5-5862-f60a-6e8d33a77bc2"
      },
      "devicegroup": {
        "type": "development_devicegroup",
        "id": "6d34ace0-e952-6667-81e6-012406e5aa98"
      },
      "deployment": {
        "type": "deployment",
        "id": "3f5bae72-6c61-8128-219c-95f576b57a2c"
      }
    }
  }
}
Doing the request with options:
{
  "url": "https://api.electricimp.com/v5/logstream",
  "method": "POST",
  "headers": {
    "Content-type": "application/vnd.api+json",
    "Authorization": "[hidden]"
  },
  "json": true,
  "qs": null,
  "body": null,
  "qsStringifyOptions": {
    "arrayFormat": "repeat"
  },
  "forever": true
}

Response code: 200
Response headers: {
  "date": "Wed, 29 Jan 2020 14:29:10 GMT",
  "content-type": "application/vnd.api+json",
  "transfer-encoding": "chunked",
  "connection": "close",
  "server": "nginx/1.10.3 (Ubuntu)",
  "content-language": "en",
  "x-node": "api02",
  "cache-control": "no-cache, no-store, must-revalidate",
  "pragma": "no-cache",
  "expires": "0",
  "accept": "application/vnd.api+json",
  "x-ratelimit-limit": "30",
  "x-ratelimit-reset": "1",
  "x-ratelimit-remaining": "29",
  "strict-transport-security": "max-age=1209600"
}
Response body: {
  "data": {
    "id": "d4622be94629926cd30dd837313651674e4dd94b151c4033759a8b0002b776b27cc2fc90f6e33496520519d6",
    "type": "logstream",
    "attributes": {
      "url": "https://api.electricimp.com/v5/logstream/d4622be94629926cd30dd837313651674e4dd94b151c4033759a8b0002b776b27cc2fc90f6e33496520519d6"
    }
  }
}
ERROR: HTTP/400: impCentral API error HTTP/400
Error: { Error: impCentral API error HTTP/400
    at EventSource.eventSource.onerror (/Users/e0088611/.nvm/versions/node/v10.15.3/lib/node_modules/imp-central-impt/node_modules/imp-central-api/lib/LogStreams.js:116:37)
    at EventSource.emit (events.js:189:13)
    at _emit (/Users/e0088611/.nvm/versions/node/v10.15.3/lib/node_modules/imp-central-impt/node_modules/eventsource/lib/eventsource.js:242:17)
    at ClientRequest.<anonymous> (/Users/e0088611/.nvm/versions/node/v10.15.3/lib/node_modules/imp-central-impt/node_modules/eventsource/lib/eventsource.js:155:9)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13) _statusCode: 400, _body: null }
The log stream is lost. Trying to reconnect...
{ Error: impCentral API error HTTP/400
    at EventSource.eventSource.onerror (/Users/e0088611/.nvm/versions/node/v10.15.3/lib/node_modules/imp-central-impt/node_modules/imp-central-api/lib/LogStreams.js:116:37)
    at EventSource.emit (events.js:189:13)
    at _emit (/Users/e0088611/.nvm/versions/node/v10.15.3/lib/node_modules/imp-central-impt/node_modules/eventsource/lib/eventsource.js:242:17)
    at ClientRequest.<anonymous> (/Users/e0088611/.nvm/versions/node/v10.15.3/lib/node_modules/imp-central-impt/node_modules/eventsource/lib/eventsource.js:155:9)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13) _statusCode: 400, _body: null }
Error: impCentral API error HTTP/400
IMPT COMMAND FAILS
```

**Comment by deldrid1** [comment]
Fixed in #13
